version: 2.1

jobs:
  ubuntu1804-python2:
    docker:
      - image: stbtester/circleci:ubuntu1804-python2
    environment:
      python_version: 2.7
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  ubuntu1804-python3:
    docker:
      - image: stbtester/circleci:ubuntu1804-python3
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  python-package:
    docker:
      - image: stbtester/circleci:python-only
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - check-pythonpackage

commands:
  pylint:
    steps:
      - run:
          name: make check-pylint
          command: |
            tesseract --version
            make check-pylint
  pytest:
    steps:
      - run: make check-pytest
  integrationtests:
    steps:
      - run: make check-integrationtests
  check-pythonpackage:
    steps:
      - run: python3 setup.py sdist
      - run: pip3 install dist/*.tar.gz
      - run: rm -rf stbt _stbt
      - run: make check-pythonpackage

workflows:
  test_all:
    jobs:
      - python-package
      - ubuntu1804-python2
      - ubuntu1804-python3
