version: 2.1

jobs:
  ubuntu1804-python2:
    docker:
      - image: stbtester/circleci:ubuntu1804-python2
    environment:
      python_version: 2.7
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  ubuntu1804-python3:
    docker:
      - image: stbtester/circleci:ubuntu1804-python3
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  python-only:
    docker:
      - image: stbtester/circleci:python-only
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - check-pythononly

commands:
  pylint:
    steps:
      - run:
          name: make check-pylint
          command: |
            tesseract --version
            make check-pylint
  pytest:
    steps:
      - run: make check-pytest
  check-pythononly:
    steps:
      - run: make check-pythononly
  integrationtests:
    steps:
      - run: make check-integrationtests

workflows:
  test_all:
    jobs:
      - python-only
      - ubuntu1804-python2
      - ubuntu1804-python3
